version: '3.8'

services:
  mainapi:
    hostname: mainapi
    build:
      context: ./mainApi
    environment:
      - POSTGRES_PASSWORD=passwd
    ports:
      - "8080:8080"
    restart: unless-stopped
      
  proxy:
    hostname: proxy 
    build:
      context: ./proxy
    environment:
      - MAINAPI_HOST=mainapi:8080
      - AUTHAPI_HOST=authapi:8082
    ports:
      - "8081:8081"
    restart: unless-stopped
            
  authapi:
    hostname: authapi
    build:
      context: ./authApi
    environment:
      - PRIVATE_KEY_PATH=./id_ecdsa
      - REDIS_HOST=redis:6379
    ports:
      - "8082:8082"
    depends_on:
      - redis 
    restart: unless-stopped

  redis:
    container_name: redis 
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    container_name: psql_db
    hostname: psql_db
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=passwd 
      - POSTGRES_DB=todo_db
    ports:
      - "5433:5432"
    restart: unless-stopped
